export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";

export const USER_LOADED = "USER_LOADED";
export const ADMIN_LOADED = "ADMIN_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

//therapist actions
export const THERAPIST_REGISTER_SUCCESS = "THERAPIST_REGISTER_SUCCESS";
export const THERAPIST_REGISTER_FAIL = "THERAPIST_REGISTER_FAIL";
export const UPDATE_THERAPIST_FORM = "UPDATE_THERAPIST_FORM";
export const THERAPIST_LOGIN_SUCCESS = "THERAPIST_LOGIN_SUCCESS";
export const THERAPIST_LOGIN_FAIL = "THERAPIST_LOGIN_FAIL";
export const THERAPIST_LOGOUT = "THERAPIST_LOGOUT";

export const THERAPIST_LOADED = "THERAPIST_LOADED";
export const THERAPIST_AUTH_ERROR = "THERAPIST_AUTH_ERROR";
export const THERAPIST_FORGOT_PASSWORD = "THERAPIST_FORGOT_PASSWORD";
export const THERAPIST_RESET_PASSWORD = "THERAPIST_RESET_PASSWORD";

export const THERAPIST_GET_PROFILE = "THERAPIST_GET_PROFILE";
export const THERAPIST_PROFILE_ERROR = "THERAPIST_PROFILE_ERROR";
export const THERAPIST_UPDATE_PROFILE = "THERAPIST_UPDATE_PROFILE";

export const GET_THERAPISTS = "GET_THERAPISTS";
export const THERAPISTS_ERROR = "THERAPISTS_ERROR";
export const GET_THERAPIST = "GET_THERAPIST";
export const THERAPIST_ERROR = "THERAPIST_ERROR";
export const ADD_THERAPIST_IMAGE = "ADD_THERAPIST_IMAGE";

export const GET_ARTICLES = "GET_ARTICLES";
export const ARTICLES_ERROR = "ARTICLES_ERROR";
export const ADD_ARTICLE = "ADD_ARTICLE";
export const GET_ARTICLE = "GET_ARTICLE";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const GET_CONVERSATIONS = "GET_CONVERSATIONS";
export const CONVERSATIONS_ERROR = "CONVERSATIONS_ERROR";
export const NEW_CONVERSATION = "NEW_CONVERSATION";
export const GET_THERAPIST_CONVERSATION = "GET_THERAPIST_CONVERSATION";
export const SET_CURRENT_CHAT = "SET_CURRENT_CHAT";
export const CURRENT_CHAT_ERROR = "CURRENT_CHAT_ERROR";
export const NEW_MESSAGE_ERROR = "NEW_MESSAGE_ERROR";
export const NEW_MESSAGE = "NEW_MESSAGE";

export const ADD_REVIEW = "ADD_REVIEW";
export const REVIEW_ERROR = "REVIEW_ERROR";
export const GET_REVIEWS = "GET_REVIEWS";
export const UPDATE_REVIEW = "UPDATE_REVIEW ";
export const DELETE_REVIEW = "DELETE_REVIEW";

//post action
export const UPDATE_POST = "UPDATE_POST";
export const GET_POSTS = "GET_POSTS";
export const GET_POST = "GET_POST";
export const POST_ERROR = "POST_ERROR";
export const DELETE_POST = "DELETE_POST";
export const ADD_POST = "ADD_POST";
export const ADD_COMMENT = "ADD_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";
export const UPDATE_LIKES = "UPDATE_LIKES";
export const UPATE_THERAPIST_DATA = "UPATE_THERAPIST_DATA";
export const UPATE_THERAPIST_ERROR = "UPATE_THERAPIST_ERROR";

export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const UPDATE_USER_PROFILE_ERROR = "UPDATE_USER_PROFILE_ERROR";

//therapist appointment actions
export const ADD_THERAPIST_APPOINTMENT = "ADD_THERAPIST_APPOINTMENT";
export const UPDATE_THERAPIST_APPOINTMENT = "UPDATE_THERAPIST_APPOINTMENT";
export const DELETE_THERAPIST_APPOINTMENT = "DELETE_THERAPIST_APPOINTMENT";
export const THERAPIST_APPOINTMENT_ACTION_FAILED =
  "THERAPIST_APPOINTMENT_ACTION_FAILED";
export const LOAD_THERAPIST_APPOINTMENT_BY_ID =
  "LOAD_THERAPIST_APPOINTMENT_BY_ID";

//user appointment
export const ADD_USER_APPOINTMENT = "ADD_USER_APPOINTMENT";
export const CANCEL_USER_APPOINTMENT = "CANCEL_USER_APPOINTMENT";
export const USER_APPOINTMENT_FAILED = "USER_APPOINTMENT_FAILED";
