export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";

export const USER_LOADED = "USER_LOADED";
export const ADMIN_LOADED = "ADMIN_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

//therapist actions
export const THERAPIST_REGISTER_SUCCESS = "THERAPIST_REGISTER_SUCCESS";
export const THERAPIST_REGISTER_FAIL = "THERAPIST_REGISTER_FAIL";

export const THERAPIST_LOGIN_SUCCESS = "THERAPIST_LOGIN_SUCCESS";
export const THERAPIST_LOGIN_FAIL = "THERAPIST_LOGIN_FAIL";
export const THERAPIST_LOGOUT = "THERAPIST_LOGOUT";

export const THERAPIST_LOADED = "THERAPIST_LOADED";
export const THERAPIST_AUTH_ERROR = "THERAPIST_AUTH_ERROR";
export const THERAPIST_FORGOT_PASSWORD = "THERAPIST_FORGOT_PASSWORD";
export const THERAPIST_RESET_PASSWORD = "THERAPIST_RESET_PASSWORD";

export const GET_THERAPISTS = "GET_THERAPISTS";
export const THERAPISTS_ERROR = "THERAPISTS_ERROR";
export const GET_ARTICLES = "GET_ARTICLES";
export const ARTICLES_ERROR = "ARTICLES_ERROR";

//post action
